name: project0-gf180
# either manually started, or on a schedule
on: [ push, workflow_dispatch ]
jobs:

  install:
    env:
        OPENLANE_ROOT:  /home/runner/openlane
        PDK_ROOT:       /home/runner/pdk
        PDK:            gf180mcuC

    # ubuntu
    runs-on: ubuntu-latest
    steps:

    # checkout the repo to get the scripts
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    # build the user project and wrapper
    - name: pdk & openlane
      run: |
        make setup

    - name: clock GDS
      run: |
        make wrapped_vga_clock

    - name: user project wrapper GDS
      run: |
        make user_project_wrapper

#    - name: simulation
#      run: |
#        make verify-io_ports-rtl

    - name: precheck
      run: |
        make precheck
        make run-precheck


    # archive the gds and final report for the user project wrapper
    - name: Archive Wrapper GDS
      uses: actions/upload-artifact@v2
      with:
          name: Wrapper GDS
          path: /home/runner/gf180-vga-clock/gds/user_project_wrapper.gds

    - name: Archive Wrapper Signoff
      uses: actions/upload-artifact@v2
      with:
          name: Wrapper Report
          path: /home/runner/gf180-vga-clock/openlane/user_project_wrapper/runs/user_project_wrapper/reports/final_summary_report.csv
